username=user 
password= pwd
browser=firefox
URL=https://www.flipkart.com
product=cornflakes
tshirtname=Checkered Men Hooded Neck Black, Grey T-Shirt
productUrlTC03=https://www.flipkart.com/dennis-lingo-men-solid-cotton-mid-rise-slim-fit-casual-shirt/p/itm123456
