username=user 
password= pwd
browser=firefox
URL=https://www.flipkart.com
product=cornflakes
tshirtname=Checkered Men Hooded Neck Black, Grey T-Shirt
productUrlTC03=https://www.flipkart.com/dennis-lingo-men-solid-casual-blue-shirt/p/itmfd90b1e43306e
